---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
          icon: github.png

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/
          icon: reddit.png

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
          icon: youtube.png
